use serde::Deserialize;

#[derive(Debug, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum Action {
    GetTransactions,
    GetTransactionCount,
    AddTransaction,
    AddAccount,
    DeleteAccount,
    UpdateAccount,
    AddCategory,
    DeleteCategory,
    UpdateCategory,
    UpdateTransaction,
    DeleteTransaction,
    AddAppconstant,
    UpdateAppconstant,
    DeleteAppconstant,
    DeleteData,
    GetAllUserBalances,
    UpdateUserBalances,
    SyncSplitData,
    InsertSplitData,
    GetDirtySplitData,
    FetchFriendLedger,
    FetchSplitSummary,
    DeleteSplit,
    LinkTransactionToLedgerEntry,
    GetData,
    ExportData,
    ImportData,
    UpsertCategoryBudget,
    DeleteCategoryBudget,
    StoreImageParseLog,
    SyncNotifications,
    GetNotifications,
    MarkNotificationRead,
    GetUnreadNotificationCount,
    UpsertFund,
    DeleteFund,
    FetchFunds,
    FetchFundDetail,
    AddFundEntry,
    UpdateFundEntry,
    DeleteFundEntry,
    GetDirtyFundData,
    SyncFundData,
}
