[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

[lib]
name = "sdk"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.80"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.32.1", features = ["bundled"] }
once_cell = "1.20.2"

